version: '3.8'

services:
  rag-ux:
    build:
      context: ./ux
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "5173:5173"
    restart: always
    networks:
     - rag-network
    depends_on:
     - backend
  backend:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
     - "8000:8000"
    restart: always
    networks:
     - rag-network

networks:
  rag-network:
    driver: bridge